#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLBH")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHang12(Hang12 instance);
    partial void UpdateHang12(Hang12 instance);
    partial void DeleteHang12(Hang12 instance);
    partial void InsertHoaDon12(HoaDon12 instance);
    partial void UpdateHoaDon12(HoaDon12 instance);
    partial void DeleteHoaDon12(HoaDon12 instance);
    partial void InsertHoaDonChiTiet12(HoaDonChiTiet12 instance);
    partial void UpdateHoaDonChiTiet12(HoaDonChiTiet12 instance);
    partial void DeleteHoaDonChiTiet12(HoaDonChiTiet12 instance);
    partial void InsertKhachHang12(KhachHang12 instance);
    partial void UpdateKhachHang12(KhachHang12 instance);
    partial void DeleteKhachHang12(KhachHang12 instance);
    partial void InsertLichSuGia12(LichSuGia12 instance);
    partial void UpdateLichSuGia12(LichSuGia12 instance);
    partial void DeleteLichSuGia12(LichSuGia12 instance);
    partial void InsertLoaiHang12(LoaiHang12 instance);
    partial void UpdateLoaiHang12(LoaiHang12 instance);
    partial void DeleteLoaiHang12(LoaiHang12 instance);
    partial void InsertNhaCungCap12(NhaCungCap12 instance);
    partial void UpdateNhaCungCap12(NhaCungCap12 instance);
    partial void DeleteNhaCungCap12(NhaCungCap12 instance);
    partial void InsertNhanVien12(NhanVien12 instance);
    partial void UpdateNhanVien12(NhanVien12 instance);
    partial void DeleteNhanVien12(NhanVien12 instance);
    partial void InsertTrinhDo12(TrinhDo12 instance);
    partial void UpdateTrinhDo12(TrinhDo12 instance);
    partial void DeleteTrinhDo12(TrinhDo12 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DAL.Properties.Settings.Default.QLBHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Hang12> Hang12s
		{
			get
			{
				return this.GetTable<Hang12>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon12> HoaDon12s
		{
			get
			{
				return this.GetTable<HoaDon12>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonChiTiet12> HoaDonChiTiet12s
		{
			get
			{
				return this.GetTable<HoaDonChiTiet12>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang12> KhachHang12s
		{
			get
			{
				return this.GetTable<KhachHang12>();
			}
		}
		
		public System.Data.Linq.Table<LichSuGia12> LichSuGia12s
		{
			get
			{
				return this.GetTable<LichSuGia12>();
			}
		}
		
		public System.Data.Linq.Table<LoaiHang12> LoaiHang12s
		{
			get
			{
				return this.GetTable<LoaiHang12>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap12> NhaCungCap12s
		{
			get
			{
				return this.GetTable<NhaCungCap12>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien12> NhanVien12s
		{
			get
			{
				return this.GetTable<NhanVien12>();
			}
		}
		
		public System.Data.Linq.Table<TrinhDo12> TrinhDo12s
		{
			get
			{
				return this.GetTable<TrinhDo12>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hang12")]
	public partial class Hang12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaH;
		
		private string _TenH;
		
		private string _DonVT;
		
		private System.Nullable<int> _DonG;
		
		private string _MaL;
		
		private string _MaNCC;
		
		private System.Nullable<int> _SLC;
		
		private EntitySet<HoaDonChiTiet12> _HoaDonChiTiet12s;
		
		private EntitySet<LichSuGia12> _LichSuGia12s;
		
		private EntityRef<LoaiHang12> _LoaiHang12;
		
		private EntityRef<NhaCungCap12> _NhaCungCap12;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHChanging(string value);
    partial void OnMaHChanged();
    partial void OnTenHChanging(string value);
    partial void OnTenHChanged();
    partial void OnDonVTChanging(string value);
    partial void OnDonVTChanged();
    partial void OnDonGChanging(System.Nullable<int> value);
    partial void OnDonGChanged();
    partial void OnMaLChanging(string value);
    partial void OnMaLChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnSLCChanging(System.Nullable<int> value);
    partial void OnSLCChanged();
    #endregion
		
		public Hang12()
		{
			this._HoaDonChiTiet12s = new EntitySet<HoaDonChiTiet12>(new Action<HoaDonChiTiet12>(this.attach_HoaDonChiTiet12s), new Action<HoaDonChiTiet12>(this.detach_HoaDonChiTiet12s));
			this._LichSuGia12s = new EntitySet<LichSuGia12>(new Action<LichSuGia12>(this.attach_LichSuGia12s), new Action<LichSuGia12>(this.detach_LichSuGia12s));
			this._LoaiHang12 = default(EntityRef<LoaiHang12>);
			this._NhaCungCap12 = default(EntityRef<NhaCungCap12>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaH
		{
			get
			{
				return this._MaH;
			}
			set
			{
				if ((this._MaH != value))
				{
					this.OnMaHChanging(value);
					this.SendPropertyChanging();
					this._MaH = value;
					this.SendPropertyChanged("MaH");
					this.OnMaHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenH", DbType="NVarChar(50)")]
		public string TenH
		{
			get
			{
				return this._TenH;
			}
			set
			{
				if ((this._TenH != value))
				{
					this.OnTenHChanging(value);
					this.SendPropertyChanging();
					this._TenH = value;
					this.SendPropertyChanged("TenH");
					this.OnTenHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVT", DbType="NChar(10)")]
		public string DonVT
		{
			get
			{
				return this._DonVT;
			}
			set
			{
				if ((this._DonVT != value))
				{
					this.OnDonVTChanging(value);
					this.SendPropertyChanging();
					this._DonVT = value;
					this.SendPropertyChanged("DonVT");
					this.OnDonVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonG", DbType="Int")]
		public System.Nullable<int> DonG
		{
			get
			{
				return this._DonG;
			}
			set
			{
				if ((this._DonG != value))
				{
					this.OnDonGChanging(value);
					this.SendPropertyChanging();
					this._DonG = value;
					this.SendPropertyChanged("DonG");
					this.OnDonGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaL", DbType="NChar(10)")]
		public string MaL
		{
			get
			{
				return this._MaL;
			}
			set
			{
				if ((this._MaL != value))
				{
					if (this._LoaiHang12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLChanging(value);
					this.SendPropertyChanging();
					this._MaL = value;
					this.SendPropertyChanged("MaL");
					this.OnMaLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NChar(10)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._NhaCungCap12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLC", DbType="Int")]
		public System.Nullable<int> SLC
		{
			get
			{
				return this._SLC;
			}
			set
			{
				if ((this._SLC != value))
				{
					this.OnSLCChanging(value);
					this.SendPropertyChanging();
					this._SLC = value;
					this.SendPropertyChanged("SLC");
					this.OnSLCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang12_HoaDonChiTiet12", Storage="_HoaDonChiTiet12s", ThisKey="MaH", OtherKey="MaH")]
		public EntitySet<HoaDonChiTiet12> HoaDonChiTiet12s
		{
			get
			{
				return this._HoaDonChiTiet12s;
			}
			set
			{
				this._HoaDonChiTiet12s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang12_LichSuGia12", Storage="_LichSuGia12s", ThisKey="MaH", OtherKey="MaH")]
		public EntitySet<LichSuGia12> LichSuGia12s
		{
			get
			{
				return this._LichSuGia12s;
			}
			set
			{
				this._LichSuGia12s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang12_Hang12", Storage="_LoaiHang12", ThisKey="MaL", OtherKey="MaL", IsForeignKey=true)]
		public LoaiHang12 LoaiHang12
		{
			get
			{
				return this._LoaiHang12.Entity;
			}
			set
			{
				LoaiHang12 previousValue = this._LoaiHang12.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHang12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHang12.Entity = null;
						previousValue.Hang12s.Remove(this);
					}
					this._LoaiHang12.Entity = value;
					if ((value != null))
					{
						value.Hang12s.Add(this);
						this._MaL = value.MaL;
					}
					else
					{
						this._MaL = default(string);
					}
					this.SendPropertyChanged("LoaiHang12");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap12_Hang12", Storage="_NhaCungCap12", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public NhaCungCap12 NhaCungCap12
		{
			get
			{
				return this._NhaCungCap12.Entity;
			}
			set
			{
				NhaCungCap12 previousValue = this._NhaCungCap12.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap12.Entity = null;
						previousValue.Hang12s.Remove(this);
					}
					this._NhaCungCap12.Entity = value;
					if ((value != null))
					{
						value.Hang12s.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("NhaCungCap12");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonChiTiet12s(HoaDonChiTiet12 entity)
		{
			this.SendPropertyChanging();
			entity.Hang12 = this;
		}
		
		private void detach_HoaDonChiTiet12s(HoaDonChiTiet12 entity)
		{
			this.SendPropertyChanging();
			entity.Hang12 = null;
		}
		
		private void attach_LichSuGia12s(LichSuGia12 entity)
		{
			this.SendPropertyChanging();
			entity.Hang12 = this;
		}
		
		private void detach_LichSuGia12s(LichSuGia12 entity)
		{
			this.SendPropertyChanging();
			entity.Hang12 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon12")]
	public partial class HoaDon12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaKH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _MaNV;
		
		private EntitySet<HoaDonChiTiet12> _HoaDonChiTiet12s;
		
		private EntityRef<KhachHang12> _KhachHang12;
		
		private EntityRef<NhanVien12> _NhanVien12;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public HoaDon12()
		{
			this._HoaDonChiTiet12s = new EntitySet<HoaDonChiTiet12>(new Action<HoaDonChiTiet12>(this.attach_HoaDonChiTiet12s), new Action<HoaDonChiTiet12>(this.detach_HoaDonChiTiet12s));
			this._KhachHang12 = default(EntityRef<KhachHang12>);
			this._NhanVien12 = default(EntityRef<NhanVien12>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10)")]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._KhachHang12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon12_HoaDonChiTiet12", Storage="_HoaDonChiTiet12s", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<HoaDonChiTiet12> HoaDonChiTiet12s
		{
			get
			{
				return this._HoaDonChiTiet12s;
			}
			set
			{
				this._HoaDonChiTiet12s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang12_HoaDon12", Storage="_KhachHang12", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public KhachHang12 KhachHang12
		{
			get
			{
				return this._KhachHang12.Entity;
			}
			set
			{
				KhachHang12 previousValue = this._KhachHang12.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang12.Entity = null;
						previousValue.HoaDon12s.Remove(this);
					}
					this._KhachHang12.Entity = value;
					if ((value != null))
					{
						value.HoaDon12s.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("KhachHang12");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien12_HoaDon12", Storage="_NhanVien12", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public NhanVien12 NhanVien12
		{
			get
			{
				return this._NhanVien12.Entity;
			}
			set
			{
				NhanVien12 previousValue = this._NhanVien12.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien12.Entity = null;
						previousValue.HoaDon12s.Remove(this);
					}
					this._NhanVien12.Entity = value;
					if ((value != null))
					{
						value.HoaDon12s.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("NhanVien12");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonChiTiet12s(HoaDonChiTiet12 entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon12 = this;
		}
		
		private void detach_HoaDonChiTiet12s(HoaDonChiTiet12 entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon12 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonChiTiet12")]
	public partial class HoaDonChiTiet12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHD;
		
		private string _MaH;
		
		private System.Nullable<int> _SoLuong;
		
		private EntityRef<Hang12> _Hang12;
		
		private EntityRef<HoaDon12> _HoaDon12;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(string value);
    partial void OnMaHDChanged();
    partial void OnMaHChanging(string value);
    partial void OnMaHChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public HoaDonChiTiet12()
		{
			this._Hang12 = default(EntityRef<Hang12>);
			this._HoaDon12 = default(EntityRef<HoaDon12>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._HoaDon12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaH
		{
			get
			{
				return this._MaH;
			}
			set
			{
				if ((this._MaH != value))
				{
					if (this._Hang12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHChanging(value);
					this.SendPropertyChanging();
					this._MaH = value;
					this.SendPropertyChanged("MaH");
					this.OnMaHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang12_HoaDonChiTiet12", Storage="_Hang12", ThisKey="MaH", OtherKey="MaH", IsForeignKey=true)]
		public Hang12 Hang12
		{
			get
			{
				return this._Hang12.Entity;
			}
			set
			{
				Hang12 previousValue = this._Hang12.Entity;
				if (((previousValue != value) 
							|| (this._Hang12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hang12.Entity = null;
						previousValue.HoaDonChiTiet12s.Remove(this);
					}
					this._Hang12.Entity = value;
					if ((value != null))
					{
						value.HoaDonChiTiet12s.Add(this);
						this._MaH = value.MaH;
					}
					else
					{
						this._MaH = default(string);
					}
					this.SendPropertyChanged("Hang12");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon12_HoaDonChiTiet12", Storage="_HoaDon12", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public HoaDon12 HoaDon12
		{
			get
			{
				return this._HoaDon12.Entity;
			}
			set
			{
				HoaDon12 previousValue = this._HoaDon12.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon12.Entity = null;
						previousValue.HoaDonChiTiet12s.Remove(this);
					}
					this._HoaDon12.Entity = value;
					if ((value != null))
					{
						value.HoaDonChiTiet12s.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(string);
					}
					this.SendPropertyChanged("HoaDon12");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang12")]
	public partial class KhachHang12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private System.Nullable<int> _SoDT;
		
		private EntitySet<HoaDon12> _HoaDon12s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(System.Nullable<int> value);
    partial void OnSoDTChanged();
    #endregion
		
		public KhachHang12()
		{
			this._HoaDon12s = new EntitySet<HoaDon12>(new Action<HoaDon12>(this.attach_HoaDon12s), new Action<HoaDon12>(this.detach_HoaDon12s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="Int")]
		public System.Nullable<int> SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang12_HoaDon12", Storage="_HoaDon12s", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<HoaDon12> HoaDon12s
		{
			get
			{
				return this._HoaDon12s;
			}
			set
			{
				this._HoaDon12s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDon12s(HoaDon12 entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang12 = this;
		}
		
		private void detach_HoaDon12s(HoaDon12 entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang12 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuGia12")]
	public partial class LichSuGia12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaH;
		
		private System.DateTime _NgayBD;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private System.Nullable<int> _DonG;
		
		private System.Nullable<System.DateTime> _NgayCN;
		
		private EntityRef<Hang12> _Hang12;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHChanging(string value);
    partial void OnMaHChanged();
    partial void OnNgayBDChanging(System.DateTime value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnDonGChanging(System.Nullable<int> value);
    partial void OnDonGChanged();
    partial void OnNgayCNChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCNChanged();
    #endregion
		
		public LichSuGia12()
		{
			this._Hang12 = default(EntityRef<Hang12>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaH", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaH
		{
			get
			{
				return this._MaH;
			}
			set
			{
				if ((this._MaH != value))
				{
					if (this._Hang12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHChanging(value);
					this.SendPropertyChanging();
					this._MaH = value;
					this.SendPropertyChanged("MaH");
					this.OnMaHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonG", DbType="Int")]
		public System.Nullable<int> DonG
		{
			get
			{
				return this._DonG;
			}
			set
			{
				if ((this._DonG != value))
				{
					this.OnDonGChanging(value);
					this.SendPropertyChanging();
					this._DonG = value;
					this.SendPropertyChanged("DonG");
					this.OnDonGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCN", DbType="Date")]
		public System.Nullable<System.DateTime> NgayCN
		{
			get
			{
				return this._NgayCN;
			}
			set
			{
				if ((this._NgayCN != value))
				{
					this.OnNgayCNChanging(value);
					this.SendPropertyChanging();
					this._NgayCN = value;
					this.SendPropertyChanged("NgayCN");
					this.OnNgayCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hang12_LichSuGia12", Storage="_Hang12", ThisKey="MaH", OtherKey="MaH", IsForeignKey=true)]
		public Hang12 Hang12
		{
			get
			{
				return this._Hang12.Entity;
			}
			set
			{
				Hang12 previousValue = this._Hang12.Entity;
				if (((previousValue != value) 
							|| (this._Hang12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hang12.Entity = null;
						previousValue.LichSuGia12s.Remove(this);
					}
					this._Hang12.Entity = value;
					if ((value != null))
					{
						value.LichSuGia12s.Add(this);
						this._MaH = value.MaH;
					}
					else
					{
						this._MaH = default(string);
					}
					this.SendPropertyChanged("Hang12");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiHang12")]
	public partial class LoaiHang12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaL;
		
		private string _TenL;
		
		private string _GhiChu;
		
		private EntitySet<Hang12> _Hang12s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLChanging(string value);
    partial void OnMaLChanged();
    partial void OnTenLChanging(string value);
    partial void OnTenLChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public LoaiHang12()
		{
			this._Hang12s = new EntitySet<Hang12>(new Action<Hang12>(this.attach_Hang12s), new Action<Hang12>(this.detach_Hang12s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaL", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaL
		{
			get
			{
				return this._MaL;
			}
			set
			{
				if ((this._MaL != value))
				{
					this.OnMaLChanging(value);
					this.SendPropertyChanging();
					this._MaL = value;
					this.SendPropertyChanged("MaL");
					this.OnMaLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenL", DbType="NVarChar(50)")]
		public string TenL
		{
			get
			{
				return this._TenL;
			}
			set
			{
				if ((this._TenL != value))
				{
					this.OnTenLChanging(value);
					this.SendPropertyChanging();
					this._TenL = value;
					this.SendPropertyChanged("TenL");
					this.OnTenLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHang12_Hang12", Storage="_Hang12s", ThisKey="MaL", OtherKey="MaL")]
		public EntitySet<Hang12> Hang12s
		{
			get
			{
				return this._Hang12s;
			}
			set
			{
				this._Hang12s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hang12s(Hang12 entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang12 = this;
		}
		
		private void detach_Hang12s(Hang12 entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHang12 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap12")]
	public partial class NhaCungCap12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private string _DiaChi;
		
		private System.Nullable<int> _SoDT;
		
		private EntitySet<Hang12> _Hang12s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(System.Nullable<int> value);
    partial void OnSoDTChanged();
    #endregion
		
		public NhaCungCap12()
		{
			this._Hang12s = new EntitySet<Hang12>(new Action<Hang12>(this.attach_Hang12s), new Action<Hang12>(this.detach_Hang12s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="Int")]
		public System.Nullable<int> SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap12_Hang12", Storage="_Hang12s", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<Hang12> Hang12s
		{
			get
			{
				return this._Hang12s;
			}
			set
			{
				this._Hang12s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hang12s(Hang12 entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap12 = this;
		}
		
		private void detach_Hang12s(Hang12 entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap12 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien12")]
	public partial class NhanVien12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private System.Nullable<int> _SoDT;
		
		private string _MaTD;
		
		private EntitySet<HoaDon12> _HoaDon12s;
		
		private EntityRef<TrinhDo12> _TrinhDo12;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(System.Nullable<int> value);
    partial void OnSoDTChanged();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    #endregion
		
		public NhanVien12()
		{
			this._HoaDon12s = new EntitySet<HoaDon12>(new Action<HoaDon12>(this.attach_HoaDon12s), new Action<HoaDon12>(this.detach_HoaDon12s));
			this._TrinhDo12 = default(EntityRef<TrinhDo12>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="Int")]
		public System.Nullable<int> SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="NChar(10)")]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					if (this._TrinhDo12.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien12_HoaDon12", Storage="_HoaDon12s", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HoaDon12> HoaDon12s
		{
			get
			{
				return this._HoaDon12s;
			}
			set
			{
				this._HoaDon12s.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo12_NhanVien12", Storage="_TrinhDo12", ThisKey="MaTD", OtherKey="MaTD", IsForeignKey=true)]
		public TrinhDo12 TrinhDo12
		{
			get
			{
				return this._TrinhDo12.Entity;
			}
			set
			{
				TrinhDo12 previousValue = this._TrinhDo12.Entity;
				if (((previousValue != value) 
							|| (this._TrinhDo12.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrinhDo12.Entity = null;
						previousValue.NhanVien12s.Remove(this);
					}
					this._TrinhDo12.Entity = value;
					if ((value != null))
					{
						value.NhanVien12s.Add(this);
						this._MaTD = value.MaTD;
					}
					else
					{
						this._MaTD = default(string);
					}
					this.SendPropertyChanged("TrinhDo12");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDon12s(HoaDon12 entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien12 = this;
		}
		
		private void detach_HoaDon12s(HoaDon12 entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien12 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrinhDo12")]
	public partial class TrinhDo12 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTD;
		
		private string _TenTD;
		
		private EntitySet<NhanVien12> _NhanVien12s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDChanging(string value);
    partial void OnMaTDChanged();
    partial void OnTenTDChanging(string value);
    partial void OnTenTDChanged();
    #endregion
		
		public TrinhDo12()
		{
			this._NhanVien12s = new EntitySet<NhanVien12>(new Action<NhanVien12>(this.attach_NhanVien12s), new Action<NhanVien12>(this.detach_NhanVien12s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTD", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTD
		{
			get
			{
				return this._MaTD;
			}
			set
			{
				if ((this._MaTD != value))
				{
					this.OnMaTDChanging(value);
					this.SendPropertyChanging();
					this._MaTD = value;
					this.SendPropertyChanged("MaTD");
					this.OnMaTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTD", DbType="NVarChar(50)")]
		public string TenTD
		{
			get
			{
				return this._TenTD;
			}
			set
			{
				if ((this._TenTD != value))
				{
					this.OnTenTDChanging(value);
					this.SendPropertyChanging();
					this._TenTD = value;
					this.SendPropertyChanged("TenTD");
					this.OnTenTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDo12_NhanVien12", Storage="_NhanVien12s", ThisKey="MaTD", OtherKey="MaTD")]
		public EntitySet<NhanVien12> NhanVien12s
		{
			get
			{
				return this._NhanVien12s;
			}
			set
			{
				this._NhanVien12s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanVien12s(NhanVien12 entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo12 = this;
		}
		
		private void detach_NhanVien12s(NhanVien12 entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDo12 = null;
		}
	}
}
#pragma warning restore 1591
